#!/usr/bin/env python3
"""Regenerate components/icons/index.tsx from public/assets/icons/*.svg.

Run after adding any Figma-exported icon. Monochrome icons get `currentColor`
so nav/hover states can recolour them; multicolour icons keep their fills.

  python3 scripts/gen-icons.py
"""
import glob, os, re

SRC, OUT = 'public/assets/icons', 'components/icons/index.tsx'

# Figma's greys for single-colour icons; swapped for currentColor.
MONO_FILLS = ('#6E7074', '#AAACAE', '#0D1117', 'black')
# Prefixes/names that are multicolour and must keep their fills.
COLOUR_NAMES = {'verified', 'info', 'toast-check', 'diamond', 'image-upload',
                'star-filled', 'star-empty'}
COLOUR_PREFIXES = ('act-',)

# Brand artwork is consumed as <img> by Topbar / ui/privy-logo.tsx, not as icon
# components — inlining it would emit dead code (and one empty component).
SKIP_PREFIXES = ('logo-',)

ATTR = {
    'fill-rule': 'fillRule', 'clip-rule': 'clipRule', 'stroke-width': 'strokeWidth',
    'stroke-linecap': 'strokeLinecap', 'stroke-linejoin': 'strokeLinejoin',
    'fill-opacity': 'fillOpacity', 'stroke-opacity': 'strokeOpacity',
    'clip-path': 'clipPath', 'stop-color': 'stopColor', 'stop-opacity': 'stopOpacity',
    'mask-type': 'maskType', 'stroke-dasharray': 'strokeDasharray',
}

def to_jsx(svg, mono):
    m = re.search(r'<svg[^>]*viewBox="([^"]+)"[^>]*>(.*)</svg>', svg, re.S)
    if not m:
        return None
    view_box, inner = m.group(1), m.group(2)
    inner = re.sub(r'<g id="&#60;safe area&#62;"[^>]*>\s*</g>', '', inner)
    inner = re.sub(r'\bid="[^"]*"', '', inner)          # ids would collide once inlined
    if mono:
        for fill in MONO_FILLS:
            inner = inner.replace(f'fill="{fill}"', 'fill="currentColor"')
    inner = re.sub(r'style="([^"]*)"', lambda mm: 'style={{' + ','.join(
        "'" + re.sub(r'-(\w)', lambda k: k.group(1).upper(), p.split(':')[0].strip())
        + "':'" + p.split(':', 1)[1].strip() + "'"
        for p in mm.group(1).split(';') if ':' in p) + '}}', inner)
    for a, b in ATTR.items():
        inner = inner.replace(a + '=', b + '=')
    return view_box, re.sub(r'\s+', ' ', inner).strip()

def component_name(stem):
    return ''.join(w.capitalize() for w in re.split(r'[-_]', stem)) + 'Icon'

def is_colour(stem):
    return stem in COLOUR_NAMES or stem.startswith(COLOUR_PREFIXES)

def main():
    out = [
        '// Auto-generated by scripts/gen-icons.py from public/assets/icons.',
        '// Do not edit by hand — re-run the script after adding an icon.',
        '// Monochrome icons use currentColor so nav states can recolor them.',
        'import * as React from \'react\';', '',
        'type IconProps = React.SVGProps<SVGSVGElement>;', '',
    ]
    count = 0
    for path in sorted(glob.glob(f'{SRC}/*.svg')):
        stem = os.path.basename(path)[:-4]
        if stem.startswith(SKIP_PREFIXES):
            continue
        parsed = to_jsx(open(path, encoding='utf-8').read(), not is_colour(stem))
        if not parsed:
            print(f'  skipped (no viewBox): {stem}'); continue
        view_box, inner = parsed
        out += [
            f'export function {component_name(stem)}(props: IconProps) {{', '  return (',
            f'    <svg viewBox="{view_box}" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden {{...props}}>',
            f'      {inner}', '    </svg>', '  );', '}', '',
        ]
        count += 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write('\n'.join(out))
    print(f'{OUT}: {count} icons')

if __name__ == '__main__':
    main()
